#!/usr/bin/env python3


try:
    import sys
    import os
    ProjectConfirmed = False
    TypeOfFile = None

    while ProjectConfirmed == False:
        
        TypeOfProject = input("Insert the type of project you want to create: 1) HTML, 2) Cordova/Phonegap or 3) npm   ")
        if TypeOfProject == '1': #html
            NewHTMLProject = input("Please type 'create ' to create a default template for HTML/CSS/JS project, type delete to delete it...   ")      
            if NewHTMLProject == "create":
                if not os.path.exists("HTMLProject"):
                    os.system("mkdir HTMLProject && cd HTMLProject && touch index.html && mkdir css img js ")
                    indexhtml = open("HTMLProject/index.html", "w")
                    indexhtml.writelines('<!DOCTYPE html>\n<html>\n<meta charset="utf-8">\n<head>\n<title>Hello World</title>\n</head>\n<body>\n<link rel=stylesheet href="css/index.css">\n<marquee>\n<h1>Hello! I am an index.html page :)</h1>\n</marquee>\n<footer>\n<h6><em>Autogenerated by Template Creator</em></h6>\n</footer>\n</body>\n</html>\n')
                    indexcss = open("HTMLProject/css/index.css","w+")
                    indexcss.writelines('body{\nbackground-color:lightgoldenrodyellow;\n}\nh1{\nfont-family: Courier;\ncolor: blue\n}\n')
                    ProjectConfirmed = True
                    print("Template created. Exiting...")
                    sys.exit()

                else:
                    deleteconf= input("You have another folder with this name. If you type yes, you are going to detroy the actual folder. To abort press ctrl+c Continue? ")
                    if deleteconf == "yes":
                        os.system("rm -rf HTMLProject")
                        sys.exit(0)


            if NewHTMLProject == "delete":
                ProjectConfirmed == True
                os.system("rm -rf HTMLProject")
                print("Project deleted!")
                sys.exit(0)



            else:
                NewHTMLProject = input("Please, retype your answer. Press enter then retype ")


#================================================================================================
#npm

        if TypeOfProject == '3': 
            NewNpmProject = input("Please type 'create ' to create a default template for npm project, type delete to delete it...   ")      
            if NewNpmProject == "create":
                if not os.path.exists("MyNpmProject"):
                    os.system("mkdir MyNpmProject && cd MyNpmProject && touch index.html && mkdir css img js ")
                    indexhtml = open("MyNpmProject/index.html", "w")
                    indexhtml.writelines('<!DOCTYPE html>\n<html>\n<meta charset="utf-8">\n<head>\n<title>Hello World</title>\n</head>\n<body>\n<link rel=stylesheet href="css/index.css">\n<marquee>\n<h1>Hello! I am an index.html page :)</h1>\n</marquee>\n<footer>\n<h6><em>Autogenerated by Template Creator</em></h6>\n</footer>\n</body>\n</html>\n')
                    indexcss = open("MyNpmProject/css/index.css","w+")
                    indexcss.writelines('body{\nbackground-color:lightgoldenrodyellow;\n}\nh1{\nfont-family: Courier;\ncolor: blue\n}\n')
                    os.system("cd MyNpmProject && npm init")
                    os.system("cd MyNpmProject && touch main.js")
                    mainjs = open("main.js","w+")
                    mainjs.writelines("const {app, BrowserWindow} = require('electron')\nconst path = require('path')\nlet mainWindow\nfunction createWindow () {\nmainWindow = new BrowserWindow({\nwidth: 800,\nheight: 600,\nwebPreferences: {\n})\nmainWindow.loadFile('index.html')\nmainWindow.on('closed', function () {\nmainWindow = null\n})\n}\napp.on('ready', createWindow)\napp.on('window-all-closed', function () {\nif (process.platform !== 'darwin') app.quit()\n})\napp.on('activate', function () {\nif (mainWindow === null) createWindow()\n})")
                    ProjectConfirmed = True
                    print("Template created. Exiting...")
                    sys.exit()

                else:
                    deleteconf= input("You have another folder with this name. If you type yes, you are going to detroy the actual folder. To abort press ctrl+c Continue? ")
                    if deleteconf == "yes":
                        os.system("rm -rf MyNpmProject")
                        sys.exit(0)


            if NewNpmProject == "delete":
                ProjectConfirmed == True
                os.system("rm -rf MyNpmProject")
                print("Project deleted!")
                sys.exit(0)



            else:
                NewNpmProject = input("Please, retype your answer. Press enter then retype ")
            
            
        #To do:
        # Add main.js                       
        # Add package.json



except KeyboardInterrupt:
    print("     Terminating.. Have a good day. See you soon :) ")

#test branch










#UNSTABLE BRANCH: everything here is not stable: use this code at your own risk. 



#Working on: npm default template configuration